"""
fig3_sensitivity_curves.py — regenerate the Fig3_sensitivity sheet of
HS4_SourceData.xlsx (forward-model OMC dissociation sensitivity curves).

WHAT THIS PRODUCES
    Mean Ni/Co calcite concentrations (ppm) vs drip rate for three fast-fraction
    families (lambda_F = 0.001, 0.01, 0.1; the manuscript figure draws 0.01),
    plus 95% CI bands, on a 100-point log drip-rate grid (0.01–100 drips/min).

PARAMETERS (locked, 2026-07-20)
    mu (mean ln k_d):  Ni -3.9361940015, Co -5.5162692714  — canonical refit
        (sigma = pi/sqrt(6) fixed a priori, lambda_F = 0.01, target 15.09
        drips/min; see kd_calibration_parameters.csv, mode=refit).
    sigma_ILLUSTRATIVE = 0.22 — the deliberately narrow width DRAWN in Fig 3
        for visual clarity, per the Fig 3 caption ("sigma = 0.22 shown for
        illustrative clarity; full sigma = pi/sqrt(6) ~ 1.28 used in
        inversions"). The illustrative curves therefore do NOT pass through
        the modern calibration point; the full-sigma inversion curves do.
    Central lambda_I, aq medians, Ca, K_p, mol wt: imported from
        calibrate_kd.METALS / CA_PPB (identical quadrature kernel).

CI BANDS — provenance note
    The published bands (caption: "inert fractions lambda_I = 0.10 +/- 0.10
    (Ni) and 0.40 +/- 0.20 (Co); shaded areas are 95% confidence intervals
    from Monte Carlo simulation") are, empirically, EXACT per-family
    multiplicative factors on the mean curve — constant in V to 6 decimals
    across the whole grid (verified against the published sheet on
    2026-07-20). This is the expected structure: lambda draws rescale the
    curve rather than reshape it. The original MC script (draw
    distribution/truncation/N/seed) is not in the repository, so rather than
    re-rolling different random bands, the published factors are preserved
    verbatim below and re-applied to the re-centred means. The (lambda_F,
    lambda_I) 95% CI semantics of the published figure are therefore
    unchanged; only the central mu moves to the canonical refit.

USAGE
    python3 fig3_sensitivity_curves.py --workbook ../manuscript_figures/HS4_SourceData.xlsx
    python3 fig3_sensitivity_curves.py --csv curves_out.csv        # optional CSV dump
    (run scripts/recalc or open/resave in a spreadsheet app afterwards if other
     sheets' formula caches must be refreshed; this script writes values only.)
"""
import argparse
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from calibrate_kd import _E1, METALS, CA_PPB, Y_S   # canonical kernel & params

# ------------------------------------------------------------------ locked
CANON_MU = {"Ni": -3.9361940015, "Co": -5.5162692714}
SIGMA_ILLUSTRATIVE = 0.22
NF_FAMILIES = (0.001, 0.01, 0.1)
V_GRID = np.logspace(-2, 2, 100)          # drips/min, matches published sheet

# Published-band factors: 95% CI / mean, per (family, metal, side).
# Extracted from the published Fig3_sensitivity sheet (pre-2026-07-20 state);
# constant in V to 6 dp within each family. DO NOT re-derive casually — these
# carry the published MC (lambda_F, lambda_I) uncertainty semantics.
BAND_FACTORS = {
    0.001: {"Ni": (0.791881, 1.130262), "Co": (0.370767, 1.625713)},
    0.01:  {"Ni": (0.789829, 1.122290), "Co": (0.341222, 1.657682)},
    0.1:   {"Ni": (0.788096, 1.123599), "Co": (0.341535, 1.639584)},
}

NOTE_TEXT = (
    "2026-07-20: regenerated by calibration/fig3_sensitivity_curves.py at the "
    "canonical refit mu (Ni -3.9361940015, Co -5.5162692714; sigma_illustrative "
    "= 0.22 as per caption; full sigma = pi/sqrt(6) applies to inversions only). "
    "Previous curves used the published mu (-3.90808/-5.57161). 95% CI bands are "
    "the published per-family multiplicative factors (constant in V; see script "
    "docstring) re-applied to the re-centred means."
)


def mean_ppm(V_dripmin, metal, nF):
    """Deterministic forward curve at central parameters (ppm in calcite)."""
    m = METALS[metal]
    Xa = (1.0 - m["inertF"]) * m["aq_ppb"] / (1e6 * m["mw"])
    Ya = CA_PPB / (1e6 * 40.078)
    K0 = (m["Kp"] * Y_S) * (Xa / Ya)
    nS = 1.0 - nF
    E1 = _E1(V_dripmin / 60.0, CANON_MU[metal], SIGMA_ILLUSTRATIVE, nF)
    return K0 * (1.0 - nS * E1) * 1e3 * m["mw"]


def build_table():
    rows = []
    for nF in NF_FAMILIES:
        for V in V_GRID:
            ni = mean_ppm(V, "Ni", nF)
            co = mean_ppm(V, "Co", nF)
            fN = BAND_FACTORS[nF]["Ni"]
            fC = BAND_FACTORS[nF]["Co"]
            rows.append((nF, V, ni, ni * fN[0], ni * fN[1],
                         co, co * fC[0], co * fC[1]))
    return rows


def write_workbook(path, rows):
    import openpyxl
    wb = openpyxl.load_workbook(path)
    ws = wb["Fig3_sensitivity"]
    header_row = next(r[0].row for r in ws.iter_rows()
                      if r and r[0].value == "n_F")
    # provenance note goes in the merged note row above the table (anchor A4)
    ws["A4"] = NOTE_TEXT
    for i, vals in enumerate(rows):
        for j, v in enumerate(vals):
            ws.cell(row=header_row + 1 + i, column=1 + j, value=float(v))
    # clear any leftover rows beyond the table (defensive; sizes match today)
    for r in range(header_row + 1 + len(rows), ws.max_row + 1):
        for c in range(1, 9):
            ws.cell(row=r, column=c, value=None)
    wb.save(path)
    print(f"Wrote {len(rows)} rows to {path} [Fig3_sensitivity], "
          f"note set in A4.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workbook", help="HS4_SourceData.xlsx to update in place")
    ap.add_argument("--csv", help="optional CSV output path")
    args = ap.parse_args()

    rows = build_table()
    hdr = ("n_F,drip_rate_drips_per_min,Ni_mean_ppm,Ni_CI_lower_ppm,"
           "Ni_CI_upper_ppm,Co_mean_ppm,Co_CI_lower_ppm,Co_CI_upper_ppm")
    print(hdr)
    for r in rows[:2] + rows[-2:]:
        print(",".join(f"{x:.10g}" for x in r))

    if args.csv:
        with open(args.csv, "w") as f:
            f.write(hdr + "\n")
            for r in rows:
                f.write(",".join(f"{x:.12g}" for x in r) + "\n")
        print(f"CSV -> {args.csv}")
    if args.workbook:
        write_workbook(args.workbook, rows)


if __name__ == "__main__":
    main()
